workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
      when: always
    - if: $CI_COMMIT_TAG =~ /^do/
      when: always
    - if: $CI_COMMIT_TAG =~ /^fix/
      when: always
    - if: $CI_COMMIT_TAG =~ /^tmp/
      when: always
    - if: $CI_COMMIT_TAG =~ /^dev/
      when: always

stages:
  - build

docker-build:
 stage: build
 image: docker:20.10.8
 variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
 services:
  - docker:20.10.8-dind
 before_script:
  - apk --update add docker-compose
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
 script:
  - echo "hello."